config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'spend_imports/new'

  post 'spend_imports', to: 'spend_imports#create'

  resources :categories
  resources :spends do
    collection { get :year }
    collection { get :daily }
    collection { get :monthly }
  end
  devise_for :users
  get 'pages/index'

  get '*unmatched_route', to: 'pages#error'

  devise_scope :user do
    authenticated :user do
      root to: "spends#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "pages#index"
    end
  end

end

app/models/spend.rb
class Spend < ActiveRecord::Base

  belongs_to :user
  belongs_to :category

  validates :category, presence: true
  validates :amount, presence: true
  validates :when_at, presence: true

  def self.total_grouped_by_day(start, user_id)
    spends = where(when_at: start.beginning_of_day..Time.zone.now).where("user_id = (?)", user_id)
    spends = spends.group("date(when_at)")
    spends = spends.select('date(when_at) as when_at, sum(amount) as amount')
    spends.group_by { |o| o.when_at.to_date }
  end

  def self.total_grouped_by_month(start, user_id)
    spends = where(when_at: start.beginning_of_day..Time.zone.now).where("user_id = (?)", user_id)
    spends = spends.group("date(when_at)")
    spends = spends.select('date(when_at) as when_at, sum(amount) as amount')
    spends.group_by { |o| o.when_at.to_date.month }
  end

  def self.to_csv(options = {})
    attributes = %w{amount description when_at created_at updated_at}

    CSV.generate(options) do |csv|
      attributes.push("category")
      csv << attributes
      attributes.pop()
      all.each do |spend|
         line = attributes.map{ |attr| spend.send(attr) }
         line.push(spend.category.name)
         csv << line
      end
    end
  end

end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_spend, only: [:show, :edit, :update, :destroy]

  # GET /spends
  # GET /spends.json
  def index
    @spends = current_user.spends.all.order(when_at: :desc, created_at: :desc)
    @spends_months = @spends.group_by { |t| t.when_at.beginning_of_month }
    @sum = []


    @spends_months.each do |month, spends|
      sum = 0
      pie = {}

      spends.each do |spend|
        amount = spend.amount
        sum += amount
        if pie[spend.category.name].nil?
          pie[spend.category.name] = amount
        else
          pie[spend.category.name] += amount
        end

      end
      pie['sum'] = sum
      @sum.push(pie)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @spends.order(:when_at).to_csv(headers: true), filename: "expenses-#{Date.today}.csv" }
      format.xls #{ send_data @spends.to_csv(col_sep: "\t") }
    end
  end

  # GET /spends/1
  # GET /spends/1.json
  def show
  end

  # GET /spends/new
  def new
    @spend = current_user.spends.build
    @spend.when_at = Time.now
  end

  # GET /spends/1/edit
  def edit
  end

  # POST /spends
  # POST /spends.json
  def create
    @spend = current_user.spends.build(spend_params)

    respond_to do |format|
      if @spend.save
        format.html { redirect_to spends_path, flash: {success: 'Spend was successfully created.' }}
        format.json { render :show, status: :created, location: @spend }
      else
        format.html { render :new }
        format.json { render json: @spend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spends/1
  # PATCH/PUT /spends/1.json
  def update
    respond_to do |format|
      if @spend.update(spend_params)
        format.html { redirect_to spends_path, flash: {success: 'Spend was successfully updated.' }}
        format.json { render :show, status: :ok, location: @spend }
      else
        format.html { render :edit }
        format.json { render json: @spend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spends/1
  # DELETE /spends/1.json
  def destroy
    @spend.destroy
    respond_to do |format|
      format.html { redirect_to spends_url, flash: {success: 'Spend was successfully destroyed.' }}
      format.json { head :no_content }
    end
  end

  def year
    start = 1.year.ago.to_date.beginning_of_month>>1
    spends_by_day = Spend.total_grouped_by_month(start, current_user.id)

    @data = []

    while true
      break if start > Date.today.end_of_month
      if !spends_by_day[start.month].nil?

        amount = 0
        spends_by_day[start.month].each do |a|
          amount += a.amount
        end
        a = {
            when_at: start.strftime('%Y-%m'),
            amount: amount
        }
        @data.push(a)
      end
      start += 1.month
    end
    @data
  end

  def daily
    @data = from_spends_chart_data
  end

  def monthly
    month = params['month']
    if !month.nil?
      begin
        @data = from_spends_chart_data(month.to_date.beginning_of_month)
      rescue
        @data = []
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_spend
    @spend = Spend.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def spend_params

    p = params.require(:spend).permit(:amount, :description, :when_at, :category)
    p['when_at'] = Date.strptime(p['when_at'], '%m/%d/%Y').strftime('%Y-%m-%d')
    if p['category'] != ''
      p['category'] = Category.find(p['category'].to_i)
      p
    end
  end

  def from_spends_chart_data(start = 1.weeks.ago+1.day)
    spends_by_day = Spend.total_grouped_by_day(start, current_user.id)
    (start.to_date..Date.today).map do |date|
      {
          when_at: date,
          amount: spends_by_day[date].nil? ? 0 : (spends_by_day[date].first.try(:amount) || 0)
      }
    end
  end

end

app/helpers/spends_helper.rb
module SpendsHelper

  def spend_line_chart(url, id)
    content_tag :div, nil, data: { url: url }, id: id
  end

end

app/views/spends/_form.html.erb
<%= simple_form_for(@spend) do |f| %>

    <div class="form-inputs">
    
      <%= f.input :amount, as: :string, input_html: { data: {autonumeric: true, role: 'money', m_dec: 0, v_min: 0, v_max: 999999999, a_sign: '$ '} }, error: 'Come on! it is the most important value here!', autofocus: true %>
      <%= f.input :description %>
      <%= f.input :when_at, as: :string, input_html: { 'data-provide': "datepicker", value: @spend.when_at.strftime('%m/%d/%Y') }, error: 'You have to tell us when did you spend this money' %>
      <%= f.input :category, collection: current_user.categories.all.order(:name), prompt: "Select a category", error: 'Category is mandatory, please specify one', selected: @spend.category_id %>
    </div>

    <div class="form-actions">
      <%= link_to 'Back', spends_path, class: 'btn btn-default' %>
      <%= f.button :button, class: 'btn btn-primary' do %>
          Send <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
      <% end %>
    </div>
<% end %>

app/views/spends/edit.html.erb
<h1>Editing Spend</h1>

<%= render 'form' %>

app/views/spends/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to new_spend_path, class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-usd" aria-hidden="true"></span> Add a Spend
    <% end %>
  </div>
  <div class="col-md-6"></div>
  <div class="col-md-2">
    Download:
    <%= link_to "CSV", spends_path(format: "csv") %> |
    <%= link_to "Excel", spends_path(format: "xls") %>
  </div>
  <div class="col-md-2">
    <%= link_to "Import", spend_imports_new_path, class: "tag-tooltip",
                :data => {:toggle=>"tooltip"},
                'data-original-title' => "We only support CSV files import for the moment.",
                'data-placement' => 'right' %>
  </div>
</div>

<div class="row">
  <div class="col-md-6" id="last_year_chart" style="display: none;">
    <h3>Last Year</h3>
    <%= spend_line_chart('/spends/year.json', 'spends_chart') %>
  </div>
  <div class="col-md-6" id="last_week_chart" style="display: none;">
    <h3>Last Week</h3>
    <%= spend_line_chart('/spends/daily.json', 'week_spends_chart') %>
  </div>
</div>

<div class="row margin-top-20">
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

    <% i = 0 %>
    <% @spends_months.each do |month, spends| %>

        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="heading<%=month.strftime('%B') + month.strftime('%Y')%>">
            <h4 class="panel-title">
              <a class="<%= 'collapsed' if i != 0 %>" role="button" data-toggle="collapse" data-parent="#accordion" href="#<%= month.strftime('%B') + month.strftime('%Y') %>" aria-expanded="<%= i == 0 ? 'true' : 'false' %>" aria-controls="<%= month.strftime('%B') + month.strftime('%Y') %>">
                <%= month.strftime('%B') %> <small>(<%= month.strftime('%Y') %>)</small> <span class="pull-right"><%= number_to_currency(@sum[i]['sum'], precision: 0) %></span>
              </a>
            </h4>
          </div>
          <div id="<%= month.strftime('%B') + month.strftime('%Y') %>" class="<%= i == 0 ? 'panel-collapse collapse in' : 'panel-collapse collapse' %>" role="tabpanel" aria-labelledby="heading<%= month.strftime('%B') + month.strftime('%Y') %>">
            <div class="panel-body">
              <div class="table-responsive">
                <table class="table table-striped">
                  <thead>
                  <tr>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>When</th>
                    <th>Category</th>
                    <th colspan="2"></th>
                  </tr>
                  </thead>

                  <tbody>
                  <% spends.each do |spend| %>
                      <tr>
                        <td><%= link_to number_to_currency(spend.amount, precision: 0), spend %></td>
                        <td><%= spend.description %></td>
                        <td><%= spend.when_at.to_date.to_s(:long) %></td>
                        <td><%= spend.category.name %></td>
                        <td>
                          <%= link_to edit_spend_path(spend) do %>
                              <span class="glyphicon glyphicon-pencil"></span> Edit
                          <% end %>
                        </td>
                        <td>
                          <%= link_to spend, method: :delete, data: { confirm: 'Are you sure?' } do %>
                              <span class="glyphicon glyphicon-trash"></span> Delete
                          <% end %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <%= pie_chart @sum[i].except('sum') %>
                </div>
                <div class="col-md-6" id="last_month_chart" style="display: none;">
                  <% if i == 0 %>
                      <%= spend_line_chart("/spends/monthly.json?month=#{month}", 'month_spends_chart') %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% i = i + 1 %>
    <% end %>
  </div>
</div>

app/views/spends/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Amount</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">When</Data></Cell>
        <Cell><Data ss:Type="String">Created</Data></Cell>
        <Cell><Data ss:Type="String">Updated</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
      </Row>
      <% @spends.each do |spend| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= spend.amount %></Data></Cell>
            <Cell><Data ss:Type="String"><%= spend.description %></Data></Cell>
            <Cell><Data ss:Type="String"><%= spend.when_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= spend.created_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= spend.updated_at %></Data></Cell>
            <Cell><Data ss:Type="String"><%= spend.category.name %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/spends/new.html.erb
<h1>New Spend</h1>

<%= render 'form' %>

app/views/spends/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@spend.amount, precision: 0) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spend.description %>
</p>

<p>
  <strong>When:</strong>
  <%= @spend.when_at.to_date.to_s(:long) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @spend.category.name %>
</p>

<%= link_to 'Edit', edit_spend_path(@spend) %> |
<%= link_to 'Back', spends_path %>