config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'spend_imports/new'

  post 'spend_imports', to: 'spend_imports#create'

  resources :categories
  resources :spends do
    collection { get :year }
    collection { get :daily }
    collection { get :monthly }
  end
  devise_for :users
  get 'pages/index'

  get '*unmatched_route', to: 'pages#error'

  devise_scope :user do
    authenticated :user do
      root to: "spends#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "pages#index"
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :user
  has_one :spend, dependent: :restrict_with_exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_user.categories.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, flash: {success: 'Category was successfully created.' }}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, flash: {success: 'Category was successfully updated.' }}
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    begin
      @category.destroy
      flash[:success] = 'Category was successfully destroyed.'
    rescue
      flash[:danger] = 'Category can not be destroyed because there are spends using it.'
    end

    respond_to do |format|
      format.html { redirect_to categories_url}
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= link_to 'Back', categories_path %>
    <%= f.button :button, class: 'btn btn-primary' do %>
        Send <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
    <% end %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to new_category_path, class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-usd" aria-hidden="true"></span> Add a Category
    <% end %>
  </div>
</div>

<div class="row">
  <h1>Your Categories</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @categories.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.name %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>