config/routes.rb
Rails.application.routes.draw do

  get 'settings/index'

  get 'spend_imports/new'

  post 'spend_imports', to: 'spend_imports#create'

  resources :categories
  resources :spends do
    collection { get :year }
    collection { get :daily }
    collection { get :monthly }
  end
  devise_for :users
  get 'pages/index'

  get '*unmatched_route', to: 'pages#error'

  devise_scope :user do
    authenticated :user do
      root to: "spends#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "pages#index"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Money</title>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Money', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li>
              <%= gravatar_image_tag(current_user.email, :alt => current_user.email, :gravatar => { :size => 50 }) %>
            </li>
            <li>
              <%= link_to 'Settings', settings_index_path %>
            </li>
            <li>
              <%= link_to 'Spends', spends_path %>
            </li>
            <li>
              <%= link_to 'Categories', categories_path %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
        <% else %>
            <li>
              <%= link_to "Sign In", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_path, class: "button" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, content_tag(:a, 'X', 'data-dismiss': "alert", class: "close") + msg, class: "alert alert-#{name}") %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>